image:
- Visual Studio 2022
- Ubuntu
build: off
init:
- ps: gcim Win32_OperatingSystem | % { "$([int]($_.TotalVisibleMemorySize/1mb)) Gb" }
install:
- ps: docker run mcr.microsoft.com/windows:1809 cmd /k "echo hello"
